### PR TITLE
SwiftUI preview for SFSymbolButton

### PR DESCRIPTION
**Pull request by mariob**

### CODE REVIEW

**Comment by emin-grbo** [comment]
Did not have enough time today to check this out properly and consider the changes, hope to have more time tomorrow 👌
but i think i am 90% sure we will be adding those as well, just want to make sure we don't add them and then figure out not all views can have them 😅

**Comment by mariob** [comment]
Tell me if you decide to do it, I can help out doing some more previews.

**Comment by emin-grbo** [comment]
Yeah, i just started to work on one view and actually came here to pick up the preview as i wanted to work on one that does the preview in both modes....that pretty much settles it! 👌

**Comment by emin-grbo** [comment]
.previewLayout(PreviewLayout.sizeThatFits) - is pure stroke of genius, i never even knew that one existed, bloody good job!

**Review by emin-grbo — APPROVED** [review]

**Comment by mariob** [comment]
Glad you liked it! I think previews are really nice (when they work).  It can boost productivity a lot and is one of those advantages you get with SwiftUI compared to other environments.

**Pull request merged**
