### PR TITLE
Added Slider to the CircleGraph preview

### PR DESCRIPTION
**Pull request by mariob**
The user can interact with the CircleGraph in the preview

### CODE REVIEW

**Review by emin-grbo — APPROVED** [review]
👌

**Comment by emin-grbo** [comment]
All good! And its well isolated in the preview!
Btw, are you able to merge yourself once i approve? I don`t want to take out the satisfaction out of merging and deleting branches from you 😆

**Comment by mariob** [comment]
No, I don't have write access 😁

**Comment by emin-grbo** [comment]
Roger that, will give that access now, and will try to setup that we are unable to merge until its approved. So in that case, whenever approval is there, feel free to merge :) 

Who knows, in time i might add some tests and other bells and whistles 👍

**Comment by mariob** [comment]
Great! Thanks 👍

**Comment by mariob** [comment]
Do you have any preferred merge strategy?

**Comment by emin-grbo** [comment]
Not really, no...to be honest i never considered it for this project as i thought it would be kind of a slow repo and mostly personal. 😅
I love "three flow" the most. Open to suggestions.

Basically MAIN - CANDIDATE - RELEASE or whatever naming we end up with

**Pull request merged**
